name: tests

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
        php: [ 8.2, 8.3 ]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout skeleton code
        uses: actions/checkout@v4
        with:
          path: 'skeleton'
          repository: 'laravel/laravel'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Execute lint tests
        run: vendor/bin/pint --test

      - name: Execute tests
        run: vendor/bin/phpunit
